### ISSUE TITLE
can't launch `elonapluscgx.exe`

### ISSUE THREAD

**Issue by wontoncc** [Ruin0x11/ElonaPlusCustom_GX#1]
An error dialog box says `No DLL: hsplua.dll` despite of `hsplua.dll` being in the same directory with  `elonapluscgx.exe`.

`error.txt` found in the same directory:
```
HspError 18 WinError 5 Line -1 Ver 6050 Mode 0
Message (JP): 代入できない変数名を指定しています
Message (EN): Wrong valiable name
efId 0 efP 0 Area 0/0
ci 0#0 ti 0#0 cc 0#0 tc 0#0 rc 0#0
3. del_userTemp ct:0
2. del_userNpc ct:0
1. userNpc_update:Replace bmp ct:0
0. Lua init ct:0
```

Tried copying `hsplua.dll` to `C:\Windows\`, but no luck. Am I missing something?

**Comment by Ruin0x11** [comment]
Confirmed on my other machine. Could you try downloading the release again [here](https://github.com/Ruin0x11/ElonaPlusCustom-GX/releases/tag/2.05.1.0)? I replaced `hsplua.dll` with an updated version.

**Comment by wontoncc** [comment]
Now it works. Thanks!
