### ISSUE TITLE
Crash when NPCs in towns urinate

### ISSUE THREAD

**Issue by ambersagrath** [Ruin0x11/ElonaPlusCustom_GX#102]
HspError 7 WinError 0 Line -1 Ver 6120 Mode 0
Message (JP): ”z—ñ‚Ì—v‘f‚ª–³Œø‚Å‚·
Message (EN): Array overflow
efId 408 efP 265 Area 5/1
ci -1#93 ti -1#54 cc 71#41 tc 71#41 rc 71#41
3. main_init:Begin ct:245
2. main_init:End ct:0
1. pc_turn_init ct:0
0. turn_end:pc ct:0

I get this error and the game crashes whenever an NPC urinates in town. A townie gets drunk either from me giving them alcohol or them getting drunk on their own. The drunkenness itself does not crash only the urine crashes the game. This doesn't happen when NPCs urinate in the wilderness or in dungeons, only in towns. I hear the urine sound play every time before the game crashes and it's very repeatable. I've had it happen several times in Vernis, Palmia, Derphy, and Lumiest. I'm on the latest Elona Plus 2.12 version and ElonaPlusCustom-GX version.

**Comment by Ruin0x11** [comment]
Fixed in 2.12.1.1.
