### ISSUE TITLE
Windows Defender Finds Malware

### ISSUE THREAD

**Issue by tkrow** [Ruin0x11/ElonaPlusCustom_GX#103]
Whenever I downloaded the program windows defender found a piece of malware in the elonapluscgx.exe file.

This is the specific malware found: Win32/Contebrew.A!ml

Is this something you guys need to look into?

**Comment by Ruin0x11** [comment]
No, this is a false positive. It seems to be picked up from any executable the HSP 3 compiler produces (even a "hello world"-type program).

**Comment by tkrow** [comment]
Okay. Thank you.
