### ISSUE TITLE
sprites for buildings are misaligned on high DPI

### ISSUE THREAD

**Issue by jacklinzoho** [Ruin0x11/ElonaPlusCustom_GX#104]
This is what it looks like with DPI of 2.0.

![elona](https://user-images.githubusercontent.com/15973776/166885534-64da3d88-e48f-4090-832b-0c39324aee85.png)

**Comment by Ruin0x11** [comment]
This is a known limitation of the smoothing algorithm (it's provided by the HSP runtime itself). You can disable `High DPI Smoothing` in the graphics options to fix this.
