### ISSUE TITLE
completing womanizer quest crashes game

### ISSUE THREAD

**Issue by totallynotabear** [Ruin0x11/ElonaPlusCustom_GX#105]
crash log:

HspError 7 WinError 0 Line -1 Ver 6120 Mode 0
Message (JP): ”z—ñ‚Ì—v‘f‚ª–³Œø‚Å‚·
Message (EN): Array overflow
efId 830 efP 0 Area 11/1
ci -1#55 ti 0#7 cc 57#223 tc 0#0 rc 2#246
3. main_init:Begin ct:245
2. main_init:End ct:0
1. pc_turn_init ct:0
0. turn_end:pc ct:0

quest can be completed in regular elonaplus, isolating the problem to custom gx

version 2.12

I gave Raphael a none human pet to finish the quest.

on further experimentation, completing the quest in regular plus, save, reopen in custom gx, still crashes game.

completing the quest in regular plus, wait until status ailments run out for quest giver, re-opens in custom gx. does NOT crash game. crash seems to be more specifically tied to Raphael the quest giver's status ailments

**Comment by totallynotabear** [comment]
it seems getting any NPC in town insane crashes game

**Comment by totallynotabear** [comment]
seems to be related to "block dust generation" setting. game won't crash if this setting is off

**Comment by Ruin0x11** [comment]
Fixed in 2.12.1.1.
