### ISSUE TITLE
Custom mp3's on certain maps cause harsh audible static.

### ISSUE THREAD

**Issue by adecrepitcabbage** [Ruin0x11/ElonaPlusCustom_GX#107]
I can't be certain that it's a custom mp3 issue, or a Custom/Elona+ issue, but I'd like to file it here in case anyone can figure out what's happening. I've used a music pack since Elona classic, which plays Atlantean Twilight as the home theme. At music start  - when loading into the map - or when the music loops, there is a very harsh loud static sound. It's jarring, and about twice the volume of the game, noticeable even with the volume turned down.

I've tried checking the musiclist that E+ 2.12 uses (which, contrary to the wiki, includes mcreset), tried disabling mcreset, tried adding a silent loop mp3, compatabilities, the whole nine yards. Any ssuggestions would be incredibly appreciated.

Build; Elona 2.12 with Custom-GX placed over it.

PC; Win 8.1, don't know if stats are necessary.

No other audible problems, with music playback, sound design, anything. I'm pretty stumped!

**Comment by jacklinzoho** [comment]
I remember having this problem a while ago, it's a base Elona issue.  It's caused by ID3v2 metadata, which is added to the front of the file.  You'll get a similar problem with ID3v1 (at end of file).  The workaround is to just strip the metadata using e.g. foobar2000.

**Comment by adecrepitcabbage** [comment]
> I remember having this problem a while ago, it's a base Elona issue. It's caused by ID3v2 metadata, which is added to the front of the file. You'll get a similar problem with ID3v1 (at end of file). The workaround is to just strip the metadata using e.g. foobar2000.

That's crazy?! It never used to be a problem before, too, *weird* but - pow, fixed. You're great, thanks pal! Now I can go back to working on my dialogue mod... Closing this issue.
