### ISSUE TITLE
Errors when trying to compile

### ISSUE THREAD

**Issue by tsuginiomaewa** [Ruin0x11/ElonaPlusCustom_GX#12]
I downloaded the repository to compile an .exe, both to be more up to date and in case I wanted to effectively screw around a bit and mod my copy of Elona.
When I tried to compile (F5) with hsed (Using main.hsp in the 2.05-custom-gx folder), it ran into a few problems. I managed to fix them in the downloaded repository, and thought it might be best to point them out since I don't know how to suggest changes or anything.
They're nothing big, just minor slips that prevent it from compiling.

Item.hsp, Line 4204, Error 5. (Translated to unclosed parentheses)
Text is as follows:
txt lang("しかしすぐに花の養分に変えられた。", "But " + he(tc) + " rapidly breaks it down into nutrients for " + his(tc) + " flowers."
The brackets around lang aren't closed. Just throw a ) on the end and call it a day.
Suggestion:
txt lang("しかしすぐに花の養分に変えられた。", "But " + he(tc) + " rapidly breaks it down into nutrients for " + his(tc) + " flowers.")

Command.hsp, Line 5888. Error 5.
Text is as follows:
txt lang(cdatan(CDATAN_NAME, cnt) + "「やめなさい！ジュア様が嫌だと言っているでしょう！？」", lang(cdatan(CDATAN_NAME, cnt) + ": \"Stop this at once! Lady Jua says she doesn't want to!\"")
There's an extra lang(. Just remove it.
Suggestion:
txt lang(cdatan(CDATAN_NAME, cnt) + "「やめなさい！ジュア様が嫌だと言っているでしょう！？」", cdatan(CDATAN_NAME, cnt) + ": \"Stop this at once! Lady Jua says she doesn't want to!\"")

Proc.hsp, Line 16126. Error 4. (Translated to unhandled expression usage, something like that)
Text is as follows:
txt lang(name(tc) + "は自分が分析されていることを逆に分析し、動きを変えた。", name(tc) + " noticed " he(tc) + " was being analyzed and changed " his(tc) + " behavior.")
Not enough usages of the +.
Suggestion:
txt lang(name(tc) + "は自分が分析されていることを逆に分析し、動きを変えた。", name(tc) + " noticed " + he(tc) + " was being analyzed and changed " + his(tc) + " behavior.")

Chat.hsp, Line 849. Error 5.
Text is as follows:
buff = lang("お前さぁ！みんなが必死こいて頑張ってるのに何帰ってんの？？自分さえよければいいとか考えてんだろ？…おい、聞いてんのかコラァァァ！！！", "Hey, YOU! Why are you leaving NOW while everyone else here is working their asses off? So you think that YOU'RE the only person that matters here, is that it? ...HEY! Are you LISTENING to me!?"
Just missing a ). Throw it on the end, call it a night
Suggestion:
buff = lang("お前さぁ！みんなが必死こいて頑張ってるのに何帰ってんの？？自分さえよければいいとか考えてんだろ？…おい、聞いてんのかコラァァァ！！！", "Hey, YOU! Why are you leaving NOW while everyone else here is working their asses off? So you think that YOU'RE the only person that matters here, is that it? ...HEY! Are you LISTENING to me!?")

Chat.hsp, Line 869. Error 4.
buff = lang("さっそくだがお前の仕事の割り当ては、仕事Ａ：" + gdata(GDATA_FLAG_WORK_A_REMAINING) + "、仕事Ｂ：" + gdata(GDATA_FLAG_WORK_B_REMAINING) + "、仕事Ｃ：" + gdata(GDATA_FLAG_WORK_C_REMAINING) + "だ。頼むぞ。", "I'll cut to the chase. Here's your work assignment. Work A: " + gdata(GDATA_FLAG_WORK_A_REMAINING) " units. Work B: " + gdata(GDATA_FLAG_WORK_B_REMAINING) + " units. Work C:" + gdata(GDATA_FLAG_WORK_C_REMAINING) + " units. Get to it.")
Only missing a single +.
Suggestion:
buff = lang("さっそくだがお前の仕事の割り当ては、仕事Ａ：" + gdata(GDATA_FLAG_WORK_A_REMAINING) + "、仕事Ｂ：" + gdata(GDATA_FLAG_WORK_B_REMAINING) + "、仕事Ｃ：" + gdata(GDATA_FLAG_WORK_C_REMAINING) + "だ。頼むぞ。", "I'll cut to the chase. Here's your work assignment. Work A: " + gdata(GDATA_FLAG_WORK_A_REMAINING) + " units. Work B: " + gdata(GDATA_FLAG_WORK_B_REMAINING) + " units. Work C:" + gdata(GDATA_FLAG_WORK_C_REMAINING) + " units. Get to it.")

Chat.hsp, Line 1548. Error 4.
chatMore lang("生還、できたのですね" + cdatan(CDATAN_NAME, CHARA_PLAYER) + "。本当によかった…。どう見ても限界を超えた力を行使していたので、ずっと心配していました。", "You really made it back alive, " + cdatan(CDATAN_NAME, CHARA_PLAYER) ". I'm so glad... I was worried about you for the longest time. You must have been exercising your powers beyond the limit of what your body was capable of.")
Missing a single +. They're important, you know!
Suggestion:
chatMore lang("生還、できたのですね" + cdatan(CDATAN_NAME, CHARA_PLAYER) + "。本当によかった…。どう見ても限界を超えた力を行使していたので、ずっと心配していました。", "You really made it back alive, " + cdatan(CDATAN_NAME, CHARA_PLAYER) + ". I'm so glad... I was worried about you for the longest time. You must have been exercising your powers beyond the limit of what your body was capable of.")

Chat.hsp, Line 14085. Error 5.
chatMore lang("まぁまぁｗｗｗ私も細かい所の埃程度は掃除してあげますけど〜そもそもの配置や片づけは" + _onii(cdata(CDATA_SEX, CHARA_PLAYER)) + "さんが自分でやってくださいねぇｗｗｗ", "just chill. lol. i can dust the tiny cracks and crevices for ya, but get off your ass and do the heavy lifting yourself, " + cdatan(CDATAN_NAME, CHARA_PLAYER) + "-san. hahaha", strbye
Missing a ). But this one's finicky! It has a strbye on the end, so we can't just recklessly throw a bracket on the end! It must be carefully inserted before it...
Suggestion:
chatMore lang("まぁまぁｗｗｗ私も細かい所の埃程度は掃除してあげますけど〜そもそもの配置や片づけは" + _onii(cdata(CDATA_SEX, CHARA_PLAYER)) + "さんが自分でやってくださいねぇｗｗｗ", "just chill. lol. i can dust the tiny cracks and crevices for ya, but get off your ass and do the heavy lifting yourself, " + cdatan(CDATAN_NAME, CHARA_PLAYER) + "-san. hahaha"), strbye

I apologize for my humor in explaining the error for the last two. Hopefully this wasn't too wall of text-y, if I can figure out how pull requests work I'll see about making the fixes myself.
Thanks for taking the time to actually read this, I hope you're well, and this issue can easily be closed/deleted/whatever when this is done.

Thank you for listening to my Ted Talk.

**Comment by Ruin0x11** [comment]
Thanks a lot for the TED Talk!

I was a bit lazy and didn't have a good commit process in place so right now I'm just committing directly to the main branch. So at the moment I haven't compiled the codebase yet, but am instead aiming to add English translations for the new text first and then fix all the errors. Right after I release that I will make sure to have a branching workflow enforced so this kind of thing won't happen in the future.

Another issue is that because HSP 3.4 has no command line compiler frontend (...seriously?) there's no easy way to put the code under continuous integration, so it's hard to tell if something breaks accidentally.

**Comment by Mirarara** [comment]
Command.hsp, Line 5888 should use \" instead of "

`txt lang(cdatan(CDATAN_NAME, cnt) + "「やめなさい！ジュア様が嫌だと言っているでしょう！？」", cdatan(CDATAN_NAME, cnt) + ": \"Stop this at once! Lady Jua says she doesn't want to!\"")`
