### ISSUE TITLE
Crash when using a plus config file.

### ISSUE THREAD

**Issue by technolem** [Ruin0x11/ElonaPlusCustom_GX#125]
You have to use an old custom config.txt, or the new one in custom's redistributable, or the game won't load.
Tested on linux.

**Comment by Ruin0x11** [comment]
I think this is a bug in standard Plus. In `original/config.txt`, there is a line that looks like this:

```
fontSize .	"14"
```

This file gets copied to `config.txt` on startup if it doesn't exist and causes the problem. Changing it to this should fix things:

```
fontSize.	"14"
```

I'll also update the `config.txt` in the package to reflect this.
