### ISSUE TITLE
Enhancements for race selection

### ISSUE THREAD

**Issue by DoctorGoat** [Ruin0x11/ElonaPlusCustom_GX#15]
I tried another mod (a prepack of omake overhaul with everything up to oomsestep) and it has a few nice features on the character select menu. I think it'd be nice to have something similar for players using extra races! 

This pack's version has speed and a list of body parts. A base character has HEAD NECK BACK BODY HANDx2 RINGx2 ARM WAIST LEG, a snail has BACK, an eye has HEAD, etc. 

Life/mana might also be good in the attribute bonus section along with speed. Seeing exact numbers as an optional ex setting for other stats during creation would be nice.

**Comment by Ruin0x11** [comment]
These are included as part of 2.06fix.2.0. Thanks for your suggestions.
