### ISSUE TITLE
gardening bug

### ISSUE THREAD

**Issue by blazer30** [Ruin0x11/ElonaPlusCustom_GX#2]
I can't view stuff in my garden because the text scroll randomizes their names. I load the game and it calls the plants some strange name.
![New Bitmap Image](https://user-images.githubusercontent.com/34281351/129432491-1d8f897f-f89c-4d99-adf3-ecfa53ecb7c1.jpg)

**Comment by Ruin0x11** [comment]
Could you try [2.06.1.0](https://github.com/Ruin0x11/ElonaPlusCustom-GX/releases/tag/2.06.1.0)?

**Comment by blazer30** [comment]
Works
