### ISSUE TITLE
Wet status doesn't wear off.

### ISSUE THREAD

**Issue by KhaozViper** [Ruin0x11/ElonaPlusCustom_GX#27]
I have thirst enabled, but disabling it didn't make any difference when I tried, and no I'm not holding a magaqua (but I did briefly grab one earlier, which I promptly disposed of with the pot for fusion) with the same save on regular E+ the wet status wears off normally.

**Comment by KhaozViper** [comment]
On further testing it did wear off in the end, it just took WAY longer (like a full in-game day or so) than on stock E+ so maybe it's still worth looking at?

**Comment by Ruin0x11** [comment]
It's definitely possible I missed something in the port to 2.05. Also there might have been someone else who reported the same issue with Wet status. I'll have to check the code and see.

**Comment by Ruin0x11** [comment]
...Yep, there it is.

https://github.com/Ruin0x11/ElonaPlusCustom-GX/commit/84f863ae3cdefe7449fa743fd22102fb4a09552f

It didn't seem to be decrementing each turn. I'll add this to the next bugfix release.

**Comment by Ruin0x11** [comment]
Should be fixed in 2.07.2.0.
