### ISSUE TITLE
Meteor crash

### ISSUE THREAD

**Issue by technolem** [Ruin0x11/ElonaPlusCustom_GX#3]
You'll need to ask neku for additional details, but here's the discord post:
https://discord.com/channels/208391609778307075/373003941979619330/876159681763086366
https://cdn.discordapp.com/attachments/373003941979619330/876159681515651132/error.txt

They meteor'd a bandit attack and it caused a type mismatch error.

**Comment by Ruin0x11** [comment]
Could you try [2.06.1.0](https://github.com/Ruin0x11/ElonaPlusCustom-GX/releases/tag/2.06.1.0)?

**Comment by technolem** [comment]
Ah, you'd need to ask neku. Haven't seen the crash since, at least.

**Comment by Ruin0x11** [comment]
Okay. It should be fixed, so I'll close this for now. If it happens again, feel free to reopen this or create a new issue.
