### ISSUE TITLE
teared tiling issue

### ISSUE THREAD

**Issue by Luciuber** [Ruin0x11/ElonaPlusCustom_GX#31]
I get major tiling issues with the current version (2.07.1.1).
Start menus, character creation menus, some in-game menus and even the map (with hdpi settings at 1.5) show a lot of tearing between disjointed tiles.
I have hdpi smoothing turned off. I couldn't find any other settings, that affected this issue. I haven't made any other adjustments or modifications.

Any ideas?

start-menu, 1280x768 :
![image](https://user-images.githubusercontent.com/93834189/140617362-28c6a863-934f-4379-ada2-6c40b8955915.png)

in-game example, 1280x768 :
![image](https://user-images.githubusercontent.com/93834189/140617256-eec26434-d39e-4b86-a58c-0ee89a3d2ce0.png)

map tearing example 800x600, hdpi=1,5 :
![image](https://user-images.githubusercontent.com/93834189/140617430-53861610-9d21-4a8b-a21f-b164a0c23f29.png)

**Comment by Ruin0x11** [comment]
Hello. This is an issue caused by the system-level scaling in Windows 10. Would you mind testing out this build and seeing if it works?

[elonapluscgx.exe](https://mega.nz/file/RqhEDBiI#ICb6yLrt2HcCrLrdfXO33RpV_E7XHObvYgG18UUdFTU)

If it does, then I'll release 2.07.1.2 with the fix.

**Comment by Luciuber** [comment]
Thanks, i tried it out.

So far the tiling issues seem to be resolved for some standard configurations:

(*edit*) With HDPI scaling at 1.0 or 1.5 all tiling issues are gone. When set to other values they occur as before.

Furthermore the game now only runs in **fullscreen mode**.

When in **window mode**, trying to load into the game (past character creation or save load) produces the following error, regardless of resolution or HDPI scaling settings:
![grafik](https://user-images.githubusercontent.com/93834189/140717702-0680d629-a8c2-4791-a6a4-ff0eb71b9a28.png)


Also: the in-game option to change HDPI Scaling _doesn't_ allow any changes.
When i change them via the config file it works as long as the resulting resolution doesnt exeed my screen resolution (as intended i suppose).
One minor issue i found with this is that in this case the ingame settings show the following:

![grafik](https://user-images.githubusercontent.com/93834189/140719157-dab92dbc-fc35-47cd-b792-372009712a40.png)

I assume the HDPI scaling line should show 1.5 (1920 *1280) to show the resulting resolution instead of 1.5 (853 * 480).

**Comment by Ruin0x11** [comment]
The crash you mentioned seems to be an issue with rendering high-quality item shadows when system-level scaling is enabled. I created a workaround to disable them if system-level scaling is detected. The resolution display in the settings should also be fixed. Both of these are part of 2.07.2.0.

I wouldn't be surprised if more scaling issues crop up, so feel free to reopen the issue if so.
