### ISSUE TITLE
Leold AP speed limit check doesn't work as intended

### ISSUE THREAD

**Issue by DiscoWitch** [Ruin0x11/ElonaPlusCustom_GX#34]
The checks to prevent you from using AP to increase speed beyond the story progression-based limit at line and 15797 in chat.hsp 
`if ( sorg(SKILL_ATTR_SPD, c) > 800 & gdata(GDATA_FLAG_MAIN) >= 350 ) {`
is wrong such that speed is uncapped in act 2 and then permanently capped at 800 in both act 3 and the endgame. The number that speed is checked against should be 500 instead of 800 in act 2, and the comparison against quest progress is backward such that it only applies after the end of act 2 instead of before.

**Comment by Ruin0x11** [comment]
Should be fixed in 2.07.2.0.
