### ISSUE TITLE
Summon Spirit summons low level spirits

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#35]
Specifically, the spirits are summoned at their base level. It also summons a random low level monster sometimes, and rarely one of the summoned spirits will be aggressive and start fighting the other spirits. The default behaviour is that the spirits should scale with the spell's level, it should only summon spirits and I think they're always friendly, though I'm not 100% sure about the last one.

This seems to have been an intentional change, though, as this has been changed at least all the way back in Custom 1.76fix. In all non-Custom versions I tested (1.41fix, 1.76fix and 2.07), the spell has the default behaviour I described above.

I'm not sure why exactly this has been changed, I think it might have had something to do with people abusing the spell to gain massive amounts of points in Party Time! quests, but this has been fixed by Ano at some point since then (summoned monster now only give at most +20 points each).

**Comment by Ruin0x11** [comment]
It seems that limiting the scaling was intentional in stock Plus, but because of a programming error it didn't take effect. I removed the limit and made the spawned creatures neutral so the spell is at least somewhat useful.
