### ISSUE TITLE
Some items missing from the list of randomly generated items

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#36]
In addition to Big Brushes being generated in random dungeons that I mentioned previously (removed in 1.94), there are also a bunch of items from recent versions that I never found after 100+ hours of play in Custom 2.07, either in dungeons or being sold by a general vendor (who seem to stock certain types of items from this list). I believe this is happening because the list of randomly generated items is outdated, as even after massive savescumming to repeteadly refresh vendors, I haven't found any of these in Custom, but was able to find all the ones that can be sold by general vendor in non-Custom. I'll list the items by version added so it's easier to pinpoint how outdated the list is:

disinfectant, added in 1.89 (vendors don't sell them and they're supposed to be rare, but I've never found one randomly)
all of the precious weapons added in 1.90 (maybe I just didn't find these because they're hard to find, though they do appear in artifact lottery)
scroll of witchcraft, added in 1.93 (same as disinfectant)
magaice, added in 1.93 (I think vendors don't sell these but they shouldn't be too rare and I've never found one in dungeons)
<ANNINDOFU LIKE A LIGHTSABRE>, added in 1.93 (generated randomly but from reading the changelogs it shouldn't be very hard to find. I did find many <Fright Prawn>, though, which was added in the same version but ISN'T generated randomly)
big brush, REMOVED in 1.94 (still spawning randomly, at least in dungeons, maybe in vendors/other places too)
kemuridama, added in 1.96 (sold by general vendor in non-Custom)
the four types of potioman, added in 2.03 (sold by general vendor in non-Custom)
filtration bottle, added in 2.05 (sold by general vendor in non-Custom)

From looking at the "Item table" article in the wiki, there seems to have been a large gap in terms of randomly spawning items added to the game before disinfectant. The previous one, bio battery, was added in 1.77 and I have found it, so it's hard to tell how outdated the list is.

Additionally, all the new weapon types added in 1.88 (kunai, fleure, tomahawk, etc), seem to be generating correctly wherever weapons can be generated (random dungeons, blacksmith shops, npc inventories, etc), although they seem to be somewhat rarer than the older types. Also, crop management tools were added to the embassy shop in 1.95 and can be found there in Custom.

Additionally, I've never found these two items that were added long ago but I think they're just super rare:

M202 special, added in 1.54 (I've only seen it once, while I was savescumming the general vendor in non-Custom, but haven't seen it yet in Custom. I have found a bunch of panzerfaust X, though, also added in 1.54)
potion of descent, added trillion years ago

**Comment by Ruin0x11** [comment]
Confirmed, I also wrote some debugging features to check the random loot tables in case this crops up again. I added the fix in 2.07.2.0.
