### ISSUE TITLE
Auto aim cheatah doesn't have its cheat

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#37]
I mean the special property it has to always crit and deal random element damage. I don't know if it gets banned.

If I'm remembering it correctly, the speed hack cheatah does have its speed hack, and I'm pretty sure I saw one getting banned once.

I don't know about the other two cheatahs.

**Comment by Ruin0x11** [comment]
Should be fixed in 2.07.2.0.
