### ISSUE TITLE
Bunch of small issues again

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#40]
Hey man, thanks for the update. Got some more small issues I forgot or overlooked or discovered recently:

In https://github.com/Ruin0x11/ElonaPlusCustom-GX/issues/36 I wrote this: ", added in 1.93 (generated randomly but from reading the changelogs it shouldn't be very hard to find. I did find many , though, which was added in the same version but ISN'T generated randomly)"
What I meant to say was: "ANNINDOFU LIKE A LIGHTSABRE, added in 1.93 (generated randomly but from reading the changelogs it shouldn't be very hard to find. I did find many Fright Prawns, though, which was added in the same version but ISN'T generated randomly)"
Looks like github cut off the item names because I had enclosed them in less-than and more-than signs, as they appear in-game. I don't know if you fixed this specifically, just a heads up if you didn't.

Forts of Chaos in South Tyris still display danger level 999. At least the Hell one does (in non-Custom it says danger level 200).

If I try to move a hostile enemy at home or in a discarded ranch with a house board/register using the "Move a stayer" function, the game crashes to desktop. You can't really move them anyway, but in non-Custom the game doesn't crash. I don't know where else the "Move a stayer" function can be used, but I assume if you fix one, you'll fix all of them.

I can't use memory converters or drug kiseru that I found in Custom in non-Custom. Memory converters are the things that drop at the end of a dungeon that halve the level of a skill in exchange for 3 skill bonus points. But if I go to non-Custom and find some, I can use them normally (though drug kiseru doesn't work in non-Custom and displays an error message instead; in Custom it works properly). I don't know if I can use the ones from non-Custom in Custom. Maybe there are other items with the same issue but I tested a few other usables and haven't found any. While this isn't really a problem in itself, this suggests some kind of difference in the code for item generation and although I haven't had any issues with items not functioning properly in Custom, this might cause problems in the future with new items. Also, this obviously would be a problem when transfering a save from Custom to non-Custom, but I hope that won't be necessary in the future...

The following three issues concern the "News" section of the journal (the very first one) and may or may not be specific to Custom or english, or english Custom:

Sometimes there will be a blank page at the end. From what I can tell, this happens if the last line in news.log is the twentieth line that appears in a journal page in-game and that line has any character on it (even a space). If that's the case, then the journal will display a blank page at the end; if that line is completely empty, then it won't. If you go and manually add a few dozen empty lines to news.log it will also display an empty page (or pages), but I guess that's to be expected. Also, this problem happens slightly more often than it should because the game leaves two empty lines at the end of news.log instead of just one for some reason.

In addition to the last page being empty, the first page of the journal also may or may not be empty (except for "- News -" on the first line) depending if the number of news pages is odd or even, so that the first page of Quest section is always on the right page.

Lastly, when there are too many news and the game adds another, sometimes it cuts off a portion of the oldest news instead of removing it completely.

**Comment by firecat6666** [comment]
Some more small issues:

One of the dialogues of Zisilion the mine king is completely empty. It's the one he has when he's ready to give you platinum but you can't receive it because you haven't done any quest yet. I think there might be some bug preventing the text from being displayed rather than it being empty because it's untranslated, as every other dialogue he has is translated.

The following two problems are from non-Custom, just putting them here in case you want to fix them (or maybe report them to Ano instead?):

The 500m Kitty Bank seems to have been removed (reasonable, considering the gold limit is around 2 billion), but the 100m Kitty Bank is mislabeled as 500m. I wished for many dozen of Kitty Banks but couldn't find one that was labeled as 100m. I don't know if japanese has this problem.

Seems you have reverted Summon Spirits to work as in non-Custom, but there it behaves really weirdly at very high levels. To begin with, the spirits only scale up to level 786. But then, if the spell's level + spellpower is too high, the spell starts summoning spirits plus some random lowish level monsters which are all level 2, friendly towards the player but aggressive towards each other (i.e.: the spirits fight the monsters, unless they monster was friendly to begin with, like a military putit; in that case it sides with the spirits). Even more strangely, when the spell level is even higher, the spells then reverts to the default behaviour.

In my case, with 464% spell power, the spell still summons high level spirits when it's level 952, but at some point between that and level 1051, the behaviour changes. I'm guessing there's some kind of overflow going on that causes the spell's behaviour to change, maybe it's related somehow to the strangely arbitrary spirit level cap of 786. Then, somewhere between spell level 1351 and level 1452 and all the way to level 2000, the spell goes back to only summoning level 786 spirits.

EDIT: after testing some more, it seems the summoned spirits level cap is the exact same number as "Deepest Lvl" stat in journal. I still have no idea why the spell starts behaving strangely at very high levels, then goes back to normal at even higher levels.

EDIT2: just found that Summon Monsters/Wild also have the weird behaviour of summoning very low level monsters at certain very high levels, seemingly within the exact same level interval as Summon Spirits.

**Comment by firecat6666** [comment]
When in wizard mode the game autosaves if the re-enable save-scumming tweak is off, which can be very annoying when I'm trying to test stuff in wizard mode and I forget to enable this tweak (always happens when I'm testing stuff on a new character). In non-Custom the game doesn't autosave at all in wizard mode. You can savescum in wizard mode regardless of the tweak.

**Comment by firecat6666** [comment]
rich person Stoke isn't selling happy apples. Since that's the last item I'm guessing the addition of Super Lure pushed it off the list. He does sell them in non-Custom.

**Comment by firecat6666** [comment]
Leold's sidequest (this one: https://elona.fandom.com/wiki/Reach_new_heights_Level_15) has a weird "name" in Custom, it's called "Next tier is equivalent to Lv". The original name is fine, although in non-Custom there's an extra unneeded space at the end of the quest name.

**Comment by firecat6666** [comment]
When changing the type of a player shop, the last two options aren't displaying correctly. The second last should have been "Decorative arts shop" but it just displays an empty line and the last should have been "Junk shop" but it says "Read what?". The names are correct in non-Custom. Also, after changing the type the name is displayed correctly in the message log.

**Comment by firecat6666** [comment]
Oblivion Palace is missing from places to return to in South Tyris. I'm not sure if it's supposed to be there in the first place, since the ability to teleport to all towns has been removed from wizard mode in non-Custom. The North Tyris list doesn't seem to be missing anything (that should be there). I'm still in South Tyris so I don't know about the next two continents.

**Comment by Ruin0x11** [comment]
A good number of these should be fixed in 2.10.1.0. Would you mind closing this issue and opening separate issues for any that got left over?

**Comment by firecat6666** [comment]
Yeah, sure. I'll check the leftover ones soon, then I'll repost them
