### ISSUE TITLE
Suggestion for a new tweak

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#43]
Under Convenience Tweaks: Using stairs at home doesn't use stamina.

Really, that's it. The changes to stamina costs for shadow step, cooking and fishing are fine and all, but this is actually the only thing that I wish cost less or no stamina.

Additionally, maybe you should move the reduced costs for cooking and fishing to a new tweak under Convenience Tweaks, since that's really what they are, in contrast to reducing the cost of Shadow Step (and then change the name of the current tweak to "Apply special action buffs" and change the description to list only the special actions affected instead of having ",and some other skills" at the end).

**Comment by firecat6666** [comment]
I think the best way to do this would be to copy the piece of code that decreases stamina when using stairs, but have the copy check if:
1-this new tweak is on
2-character is at home (maybe by having it check if current map is any of the "your home" maps)
And then add 15 stamina instead of subtracting. Maybe also exclude the part that tries damage the character when stamina is too low, if it's there.

This way you don't have to mess with any of the existing code.

**Comment by Ruin0x11** [comment]
Added in 2.10.1.0.
