### ISSUE TITLE
Disable DESTINY tweak breaks DESTINY completely

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#44]
I ran into this issue in Custom 2.07.1.1 but had forgotten about it.

When I tested the tweak I already had some of the DESTINY letters. I turned it off for some hours or something, then decided to turn if back on. Afterwards I couldn't get any more letters, except one from sleeping. I'm guessing what happens is that the game still keeps track of all the stats that trigger DESTINY but it fails to add more letters while the tweak on. Then when it's turned off, any of the stats that are already past the threshold for adding a letter won't be able to add any because they've already past the point that they would have added a letter. In my case, while I had the tweak on I was doing some training/dungeon diving, enough to trigger all the letters related to those activities but I believe I hadn't sleep enough times, then when I turned it back on the only letter I could still get was the one from sleeping.

I couldn't find any way to fix this with in-game functions, I had to use cheat engine and fill my remaining DESTINY letter, then trigger it. Afterwards it worked normally again.

**Comment by Ruin0x11** [comment]
Should be fixed in 2.08.1.0. Basically I reduced the scope of the tweak to only prevent DESTINY effects in dungeons and restore the rarity generation of equipment. The DESTINY triggers should still be accounted for with the tweak on now.
