### ISSUE TITLE
Show enchant strength for every enchant with the tweak

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#46]
I mean the tweak that lets you see enchantment magnitudes if you're holding an objet of heart. It doesn't show strength for certain enchants like maintains, floats or immunity to sleep/poison/etc. Normally this isn't a big deal since those enchants all work the same regardless of magnitude (except when eating equipment with maintains, as the strength of the attribute growth hex varies according to the enchant magnitude), but that's a pretty big problem when I'm considering which equipment to keep for artifact fusion, since EVERY randomly added enchantment has a random magnitude (except "allows quick shooting" and "enhances your rock throwing"). For example, two pieces of equipment of the same kind, rarity, material and with identical random enchants, say, maintains X, Y and Z (plus the intrinsic ones from type and material) will almost certainly have different artifact power because those enchantments would have been generated with different magnitudes.

I can check magnitudes of enchants for individual equipment with Cheat Engine/Elosnack fairly easily but it's kinda of a pain in the ass if I want to check dozens of things. Would be much easier if the magnitude of every enchant was displayed ingame instead of only some of them.

**Comment by Ruin0x11** [comment]
Added in 2.08.1.0.
