### ISSUE TITLE
Travelling message is in English when game is in Japanese

### ISSUE THREAD

**Issue by jacklinzoho** [Ruin0x11/ElonaPlusCustom_GX#49]
The Travelling xp-gain message ("you and your friends have travelled X miles", etc) is in English even when Language is set to Japanese
![screenshot](https://user-images.githubusercontent.com/15973776/147398189-b317db49-5d7b-4706-a6da-07314ac4987a.png)
.

**Comment by Ruin0x11** [comment]
Fixed in 2.08.1.0.
