### ISSUE TITLE
Bugs from non-Custom

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#51]
Sorry, I couldn't find any way to send private messages in this website and this is basically the first time I'm using it to do anything that's not downloading something. But do you want me to post bugs from non-Custom too? If not, just close this issue, otherwise leave a message and I'll put them... all here, I guess? I've written down a handful of them but I've run into a bunch, though nothing major or game-breaking. Some seem more like oversights on Ano's part and are probably easy to fix, but I'd wager most aren't.

**Comment by Ruin0x11** [comment]
I think it's fine, so long as you think they're bugs. Also, I would prefer you open a separate issue for each bug, unless they're related to each other somehow.
