### ISSUE TITLE
The tweak to prevent home stayers from moving behaves inconsistently/weirdly

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#52]
Initially I was bothered by the fact that it doesn't affect the new NPCs added in 2.06 that offer to stay in your home. Specifically, Telhureza, Scard, magic bees or young swallows. Oxode and Imarituka already don't move normally, so it doesn't really matter if the tweak isn't working for them, but I'm guessing it also isn't.

But after further investigation some incredibly bizarre behaviour emerged. For starters, it also doesn't affect almost all of the temporary visitors (though maybe that's to be expected?). I tested shopkeeper, guild trainer, citizen, beggar, punk and Mysterious Producer (I think that's all of them). However, it DOES affect visiting adventurers, at least warrior and wizard class ones, even after they've been hired and on any floor of the house.

But perhaps the most bizarre thing is that the tweak affects monsters AND pets, even including adventurers that joined your party, but ONLY on the upper floor of the house. The monsters/pets walk normally if they're on the ground floor (where all the house NPCs stay) or below. In the case of monsters, the tweak applies to them regardless of what summon spell I used, how many I summon or if they're initially hostile or friendly.

**Comment by Ruin0x11** [comment]
Should be fixed in 2.10.1.0.
