### ISSUE TITLE
(non-Custom) Monster level preview for Duel option in arena is always 3

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#55]
But the level of the monster fought does increase. I don't know if this is wrong in japanese too. The preview for Rumble seems to be correct, though I've been stuck at level 50 for a while. Maybe monsters above level 50 don't appear in the arena anymore or something.

**Comment by Ruin0x11** [comment]
Fixed in 2.08.2.0.
