### ISSUE TITLE
(non-Custom) Ano fucked up a perfectly fine translation for some reason

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#60]
When talking to an npc with 0 attract, the message says "(playername isn't paying any attention to you.)" or "(playername gazes at you with disinterest.)". Not sure when this got broken but E+ 1.41fix has semantically correct messages (which are the same messages used in vanilla, if I'm not mistaken). The other two versions I have, 1.76fix and 2.07, have the fucked up messages.

**Comment by firecat6666** [comment]
forgot to mention this isn't a Custom bug

**Comment by Ruin0x11** [comment]
Fixed in 2.08.2.0.
