### ISSUE TITLE
Missing change from 2.08fix (massive damage to metals for living weapons)

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#62]
This one: "Added the "deals massive damage to metals" equipment attribute to the list of equipment attributes that living weapons can acquire." In non-Custom it comes after massive damage to dragons in the cycle of enchants for that level up option.

The other change in 2.08fix is about fixing a crash when starting the game in english but I haven't had any crash.

**Comment by Ruin0x11** [comment]
Fixed in 2.08.2.0.
