### ISSUE TITLE
Chaos and Sound damage aren't inflicting status effects

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#63]
I tested this using a proper weapon with almost 4k chaos damage magnitude and level 1k+ chaos ball spells on 2.08fix Custom and fresh non-Custom install. Couldn't inflict any status effect on Custom but on non-Custom I could inflict all of them very easily.

I also tested Martial Arts with Attribute special action but it seems it doesn't do enough chaos damage to inflict status effects on high level enemies with high resists, which saddens me greatly.

EDIT: Sound also isn't inflicting dim.

**Comment by Ruin0x11** [comment]
Fixed in 2.08.2.0.
