### ISSUE TITLE
(non-Custom) Messed up possessive adjectives after eating forbidden meat

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#64]
After eating forbidden meat, some of the text lines which include the phrase "your somethingsomething" becomes "his/her somethingsomething" or "his?/her? somethingsomething". In non-Custom the only example I could find of this are the last items in the feats window, the ones that describe your equipment bonuses. In Custom it also appears on the text message when using Attribute and Clear Mind special actions.

Additionally, in the comments for the forbidden meat wiki page, the comment second from the top also mentions this text problem for pets. It also mentions forbidden meat possibly not working to alter gender-related evolution but I tested that and it works.

This bug goes way back, at least to 1.41fix, possibly all the way back when forbidden meat was implemented.

**Comment by firecat6666** [comment]
Specifically, this seems to happen only when the text value for "custom" gender is set to any of 6 valid options (F/M, F?/M?, none/hermaphrodite) but if it's empty it doesn't happen. So if you wish for "sex", pick female/male then don't rename the gender or rename it to something other than the 6 genders, the bug doesn't occur, but if you rename it to any of the 6 genders (even if you picked male and set the custom name to "male"), then it occurs. It also occurs when picking any of the 4 other options because they all set this "custom" gender value to one of the 6 genders.

**Comment by Ruin0x11** [comment]
Should be fixed in 2.10.1.0.
