### ISSUE TITLE
Magnitude of enchants is being displayed in feats window when show enchant strength tweak is on 2

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#65]
On the last items of the feats list, the ones that list your equipment enchants. It's only being displayed for the enchants that have their magnitude shown when the enchant strength tweak option is on 2, it doesn't show magnitudes when it's on 1 or 0. The enchants that were already included in the old version of this tweak never have their magnitude displayed in the feats window, but I don't know if this is a feature of the base game or something Custom had to add.

Additionally, if you have multiples of the same enchant but with different magnitudes, for example See invisible (100) on one equip and on another equip See Invisible (150), both are displayed when the tweak is on 2, but only one See Invisible is displayed otherwise.

**Comment by Ruin0x11** [comment]
~~Is this still an issue with the latest version? There was a bug that didn't display enchantment powers for the two recently added enchantments, so it might have actually been that issue.~~ My bad, didn't realize this was in the feats menu.

**Comment by Ruin0x11** [comment]
Fixed in 2.10.1.0.
