### ISSUE TITLE
(non-Custom) Offensive spells don't gain experience if they hit a summoned monster

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#66]
Specifically, if the last monster damaged by a bolt/ball spell or the sole monster hit by an arrow spell was a summoned one, the spell doesn't gain experience. I noticed this while I was trying to train offensive spells with the sandbag training tweak, but I'm pretty sure this has nothing to do with that tweak.

I tested this in other versions and it seems like this was changed a really long time ago, before 1.41fix but after... vanilla Elona, but I can't find any mention of this in the changelogs. So I guess it's not actually a bug, but it's pretty annoying, since summoned monsters can be used to train basically everything except single-target offensive spells (bolts/balls gain experience even if they hit nothing). Using a rod of change monster then sandbagging the monster works but if the monster is at home it vanishes when leaving and coming back, together with the sandbag.

**Comment by firecat6666** [comment]
This issue also affects non-offensive spells that you can cast on others like Healing Touch, Teleport Other, also hexes and even things like Door Creation if the targeted tile has a summoned creature in it. It also affects Casting experience gain and Magic Device if you're casting from wands.

Weirdly it also affects Healing Rain, even though it doesn't seem to ever heal creatures that can't be talked to. It seems it doesn't gain experience as long as there's a summoned creature within the AoE of the spell.

Even weirder is that ball spells actually CAN gain experience when hitting summoned creatures but only if:
1 - the creature dies
2 - the creature is located in a tile "before" the player's tile (i.e.: if the tiles were numbered with the top left one being the first and bottom right being the last)
3 - in the case of the ball spell hitting more than 1 creature, the last creature that got hit wasn't a summoned creature that didn't die AND wasn't located in a tile "after" the player's.

**Comment by Ruin0x11** [comment]
It seems this was intentional, and goes back at least as far as 1.90. To fix this I could just add another tweak that functions like the one for sandbags already.

https://github.com/Ruin0x11/ElonaPlusCustom-GX/blob/0e4feadfadf7af9e49afc593246e81c589c3e513/2.05-custom-gx/screen.hsp#L5702-L5710

**Comment by Ruin0x11** [comment]
I added a new tweak in 2.10.1.0 that makes summoned/splitting monsters give skill and spell experience. (`Gameplay Tweaks > Summoned Monster Training`)
