### ISSUE TITLE
Crop management tools isn't working properly

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#67]
It's working partially. Using it gives gardening experience and upgrades the crop by +3 as it should, but after trying it a bit with a few different types of seeds I'm getting mixed results. If it makes any difference, I'm doing this in february.

Using it on unknown seeds, the first four options, which are supposed to set the crop harvested to something specific, don't seem to be working at all. It seems I get the same assortment of random crops of the season that I get without using the tools, but with +3 higher bonus. But the fifth option, which sets the item harvested to something (completely?) random and without a + bonus, seems to be working properly.

Using it on vegetable seeds, I get the same results as with the above but on all five options instead of only the first four.

All five options seem to work properly when using it on magical and gem seeds, which don't yield items with + bonuses.

So it seems the thing works 100% correctly as long as the item harvested doesn't come with a + bonus; if it does then it fails to set the crop to something specific.

**Comment by Ruin0x11** [comment]
Should be fixed in 2.10.1.0.
