### ISSUE TITLE
(feature request) Custom AI needs a 'do-nothing' action.

### ISSUE THREAD

**Issue by jacklinzoho** [Ruin0x11/ElonaPlusCustom_GX#68]
this would be useful for conditions like:

IF (target distance >= 6) do nothing.

The difference vs just letting the AI fail is that you won't see the "doesn't know how to respond" message.  This way you can leave the message on, to debug other things, while shutting the pet up for a specific condition you already know about.

For the condition in the example, usually I do it like this:

IF (no enemies within 6 tiles) and
IF (player distance >= 1) move forward  //i.e. crowd around the PC if you have nothing better to do.

but this doesn't work for mounts.

**Comment by Ruin0x11** [comment]
Added in 2.08.2.0.
