### ISSUE TITLE
New enchants from 2.08 are missing the power display part (the [#####+] things)

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#70]
The 2 new enchants are described here: https://elona.fandom.com/wiki/Changelog_(Elona%2B)#2.08:_detailed_changelog

They're working correctly as far as I can tell, it's just that bit in the description that's missing (and inflicts massive damage to metals is missing from the level up options for living weapons but I opened an issue for this already).

**Comment by Ruin0x11** [comment]
Should be fixed in 2.08.2.0.
