### ISSUE TITLE
Wrong platinum reward for Challenge and Panic! quests

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#71]
I tested this with $x700+ quests, so maybe the reward is correct for lower level ones. They both only give 2 platinum in Custom but at that difficulty Challenge gives 3 plat and Panic! gives 6 in non-Custom. The platinum reward for the latter was changed in 1.995 but the most recent change to the former seems to have been in 1.66, to fix a bug, so I don't know why the reward is wrong.

I also tested Hunting quest but it gives 3 plat in either version. I don't know if there's anything wrong with the randomised rewards fror these quests, or with the rewards from other quests.

**Comment by Ruin0x11** [comment]
The varying amounts have to do with the fame of the character. They're also randomized, so completing quests of the same difficulty might produce different platinum amounts. However, they should always be between 2 and 6 platinum coins for Challenge/Panic!.

https://github.com/Ruin0x11/ElonaPlusCustom-GX/blob/2f83864f9b5afc53771a8690f8046f88e3868d12/2.05-custom-gx/quest.hsp#L728-L736

**Comment by firecat6666** [comment]
You're right, I just did a Challenge quest and it gave me 6 pp. My fault for cheating my platinum instead of actually doing random quests more often, lol.
