### ISSUE TITLE
(non-Custom) Game crashes when player vomits after reaching anorexia level ??

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#72]
Happens in japanese too. I ran into this while tossing cursed alcohol at myself repeteadly while testing the changes to damage from vomiting. I think this isn't related to the anorexia crash mentioned/fixed in 2.08fix.

**Comment by Ruin0x11** [comment]
Fixed in 2.08.2.0.
