### ISSUE TITLE
Linear Launcher displays wrong message when inflicting Invert (renamed to Prone in Custom)

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#73]
I'm posting this as a Custom issue but it's wrong in non-Custom too (along with every other thing that's wrong in the english version...).

It says the target was blinded. The two other things I know that cause Invert, Shield Parry and Impact Gunfire, say the target was knocked down. In non-Custom all three say the target was blinded.

**Comment by Ruin0x11** [comment]
Fixed in 2.08.2.0.
