### ISSUE TITLE
Small problem in the text for Sophia's quest

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#74]
I don't know if this quest is translated at all in non-Custom, so I'm assuming it's a Custom issue (it looks like a proper translation rather than an Ano "translation"). When getting the quest, sophia says she needs help organizing the Nth underground warehouse. seems that N is supposed to be the number of times she has offered the quest (i.e.: the times you arrived on time plus the times you missed it; at least in japanese this seems to be the case), but in english the number is displayed as NN. In other words, the first time she says she needs help with the 11th warehouse, the second time it's the 22th warehouse, then 33th warehouse... then 1010th the tenth time, 1111th the eleventh, etc.

Also, the journal entry for this quest mentions "sacred library of ylva" but only when you have accepted the quest and it's still not time to visit her (i.e.: the quest entry has a date). Otherwise it reads "sacred library of irva".

**Comment by Ruin0x11** [comment]
Fixed in 2.08.2.0.
