### ISSUE TITLE
Windows Defender detecting Uwamson.Alml on version 2.08.1.0

### ISSUE THREAD

**Issue by Roxas902** [Ruin0x11/ElonaPlusCustom_GX#75]
Upon opening the 7z file for the latest update, Windows Defender keeps warning me about this. I have not had this same issue with any past versions of Custom-GX, and only this one. I don't know if anyone else is having this issue, but whether it's a false alarm on my part or not, it does get in the way.

**Comment by firecat6666** [comment]
Try uncompressing and recompressing the file with a different compression method to see if it goes away. If not it might be the case to scan each file individually and report which one is causing problems, although I seriously doubt anyone would be trying to distribute a virus via a mod of a mod of a relatively unknown game.

**Comment by Roxas902** [comment]
I figure it's a false flag as well, just wanted to bring it up anyway since it's better off not triggering in the first place. Either way, when I re-zipped it as a zip file this time using Winrar, I didn't get the same notification from Windows Defender.
