### ISSUE TITLE
bug check please(2.08.10 / i Using a translator)

### ISSUE THREAD

**Issue by rabbitman127** [Ruin0x11/ElonaPlusCustom_GX#76]
It all happened in the Japanese version. I'm not sure about English version.

*kumiromi(npc version) skill missing

In Custom-Gx 2.08.10, didn't own it 
Special action Lovecrafting

normally skill owned by elona+ original 2.08fix

*party quest Ensemble not used

Not normally used in party quests.
Ensemble is random stopped.

*When pets eat, they interfere with their behavior (when eating automatically)

The player's character's behavior is not working properly while the pet is eating

It's hard to explain the bug, 
but I'm sorry. I can't speak English
I'm always thankful to the developer.

**Comment by Ruin0x11** [comment]
日本語を書いてもOKです。（分かるので）

**Comment by Ruin0x11** [comment]
All these issues should be fixed in 2.08.2.0.
