### ISSUE TITLE
2.08.1.0 Release Has a Trojan Virus?

### ISSUE THREAD

**Issue by ssun-1** [Ruin0x11/ElonaPlusCustom_GX#77]
I just tried to download the 2.08.1.0 release but my anti-virus states it has the trojan virus Oneeva.A!ml in it, so it gets deleted immediately.

Is this just a case of a mistaken file identity or is there something in the release that needs to be fixed?

**Comment by Ruin0x11** [comment]
I personally never got any virus warnings from downloading 2.08.1.0 and running it on my own machine. However, just to be sure I released 2.08.2.0 which should hopefully clear up any issues. Please reopen if you see it again, though.
