### ISSUE TITLE
(Almost) All elements aren't inflicting status effects

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#78]
Seems like this commit broke everything instead of fixing: https://github.com/Ruin0x11/ElonaPlusCustom-GX/commit/54296786138a85299c5fcc07377de97e08154dcf

I tested (almost) everything and even things like bleed from Cut element and the Ether disease increase from meleeing things like shining hedgehogs aren't working. The only things that are working are wet from water spells (including the arrow version, so thanks for fixing that), the occasional 1 turn paralysis from lightning damage and nether damage life leech. I didn't actually test every element but, other than the aforementioned ones, I did test fire, ice, dark, poison, sound and chaos so I'm guessing the others are all broke too.

**Comment by Ruin0x11** [comment]
Yeah, my mistake. It should be fixed (for real this time) in 59efe0f63ecf8aba81ede7d69d73ecc733418c46.
