### ISSUE TITLE
Tag index error causes bizarre results at horsemaster

### ISSUE THREAD

**Issue by DiscoWitch** [Ruin0x11/ElonaPlusCustom_GX#79]
The indices of filter_creature used to set tag filters (like "/man/" and "/horse/") are wrong in the latest version, so creatures are spawning in places where they shouldn't -- the horsemaster and the summon wild spell both produce random creatures that don't match what they should normally have.

**Comment by Ruin0x11** [comment]
Fixed in f6c383d385cf638baf2fe70d70ef937b4ce2a756.
