### ISSUE TITLE
Status effects no longer proc

### ISSUE THREAD

**Issue by EnragedWaters** [Ruin0x11/ElonaPlusCustom_GX#81]
Hiya - so I noticed with my new game that Chestnuts don't cause bleed effect.
 Others in the discord mentions special actions also don't function - such as touch of sleep and eye of mana.
 I used Wizard mode and found even other things such as Touch of Fear also weren't affecting npcs.
 
This is for Custom GX 2.10 AFTER the hotfix of the Slave Master selling monsters, and escort quests giving monster npcs as well.
 Best of luck <3

**Comment by DiscoWitch** [comment]
This is caused by the third parameter name in the dmgcon function being renamed from dmgcon_arg3 to dmgcon_power, so a bunch of references to the old name just resolve to 0 and cause statuses to not be applied.
