### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Absol19** [Ruin0x11/ElonaPlusCustom_GX#97]
Hello! I'm running the current version of custom-gx (2.10.1.1), but every time I try to start the game via elonapluscgx.exe the game crashes with the same error message:

```
HspError 12 WinError 2 Line -1 Ver 6100 Mode 0
Message (JP): ƒtƒ@ƒCƒ‹‚ªŒ©‚Â‚©‚ç‚È‚¢‚©–³Œø‚È–¼‘O‚Å‚·
Message (EN): File I/O error
efId 0 efP 0 Area 0/0
ci 0#0 ti 0#0 cc 0#0 tc 0#0 rc 0#0
3. dim ct:0
2. ctrlFile10 ct:0
1. del_userNpc ct:0
0. del_userTemp ct:0


Please check and organize the information as to what kind of thing you were doing when the error occurred, if it is reproducible, screenshot showing the problem, comparison of the results from the vanilla version. In addition, if you can use the bug reporting template on the Elona board development thread, it would help identify the cause and will be saved for reference. There is little chance it will be solved if you provide very little information or just the error code.

```
I've tried deleting the whole file and trying again, redownloading Elona+ 2.10 and custom-gx, but it continues to give me the same error.

**Comment by Ruin0x11** [comment]
Seems to be a file issue of some sort. If you don't mind, could you follow the installation steps in the README for running the game from source? That way it will provide the line number and file the error occurs in.

**Comment by Absol19** [comment]
sure thing, give me a bit to get to my pc

**Comment by Absol19** [comment]
![image](https://user-images.githubusercontent.com/19561658/161390557-237d196a-ddfc-4066-81bf-0051104fdca5.png)

This is what its giving me

**Comment by Ruin0x11** [comment]
That would mean that the `data/ndata.csv` file is missing (the data for random names). Does it exist in your install?

**Comment by Absol19** [comment]
hmm I dont see it, would I just need to grab it off another version?

**Comment by Ruin0x11** [comment]
It's supposed to be included in `elonaplus2.10.zip` (mirror [here](https://mega.nz/file/t7gy0Zpb#-3FK-dbN-KJhenuc6sGWxuIJWu7Tcz0cAcKLII_5E1w=)).

**Comment by Absol19** [comment]
ok, I redownloaded it and its working perfectly now. not sure what happened that it wasnt in there before. thank you for all your help!
