### ISSUE TITLE
Possible virus? Version 2.11.1.0

### ISSUE THREAD

**Issue by ghost** [Ruin0x11/ElonaPlusCustom_GX#98]
I scanned the latest version of Elona+ Custom-GX through VirusTotal and got these results:

![img1](https://user-images.githubusercontent.com/40591857/162645315-9fb44a94-25a2-468f-a0b9-e1df1f142e47.png)

![img2](https://user-images.githubusercontent.com/40591857/162645317-5fa86e4c-1a28-4dbc-a13a-e53d2489c5a7.png)

Hopefully these are just false positives, but it couldn't hurt to double check to make sure.

**Comment by mammalian-hominid** [comment]
Got this while running the game today. Not sure if this is relevant but it was a little worrying.
![image](https://user-images.githubusercontent.com/103963794/163870857-b7fdb22f-3966-4fd1-aa66-4712b52108c9.png)

**Comment by mammalian-hominid** [comment]
After some further research, it looks like this is likely a false positive as well, not sure if this is related to Gersado's findings

**Comment by Ruin0x11** [comment]
As far as I can tell, this is a false positive. I compiled a simple "hello world" program with the latest HSP 3 compiler and submitted it to VirusTotal, and it came back with a virus warning.
