### ISSUE TITLE
Spell Power

### ISSUE THREAD

**Issue by aaabbbaaabb** [Ruin0x11/ElonaPlusCustom_GX#99]
Excuse the machine translation, as English is difficult to understand.
Thanks for the great work!

At 400% spell power, the magic was about 3 times more powerful than non-custom.
Maybe the following noncustom 2.01 changes are not coded.

The number of dice for attack spells is no longer increased by spell power. They now behave like a lot of other spells - only their dice range will be increased when spell power increases.

Sorry if I'm wrong.

**Comment by aaabbbaaabb** [comment]
s = "" + dur + lang("ﾀｰﾝ ", "t ") + buffdesc
		return
	}
	calcskill i, cc, calcspellpower(i, cc)
	if ( cc == 0 ) {


	calcskill i, cc, calcspellpower(i, cc)　→　calcskill i, cc, calcspellpower(i, cc), calcspellpower(i, cc)

**Comment by Ruin0x11** [comment]
Fixed in 2.12.1.1.
